# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14

    environment: # environment variables for the build itself
      TEST_RESULTS: /tmp/test-results # path to where test results will be saved

    steps:
      - checkout
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p /tmp/artifacts
            mkdir -p ${TEST_RESULTS}

#      - restore_cache: # restores saved cache if no changes are detected since last run
#          keys:
#            - go-mod-v4-{{ checksum "go.sum" }}

      - run: go get -v -t -d ./...
      - run:
          command: |
            PACKAGE_NAMES=$(go list ./... | circleci tests split --split-by=timings --timings-type=classname)
            gotestsum --junitfile ${TEST_RESULTS}/gotestsum-report.xml -- -coverprofile=c.out $PACKAGE_NAMES
            go tool cover -html=c.out -o coverage.html
            mv coverage.html /tmp/artifacts
      - run: go build ./...

#      - save_cache:
#          key: go-mod-v4-{{ checksum "go.sum" }}
#          paths:
#           - "/go/pkg/mod"

      - store_artifacts:
          path: /tmp/artifacts
      - codecov/upload:
          file: /tmp/artifacts
  lint:
    docker:
      - image: golangci/golangci-lint:v1.26
    steps:
      - checkout
      - run: golangci-lint run -v
workflows:
  version: 2
  build-workflow:
    jobs:
      - lint
      - build
