# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: go build ./...
  lint:
    docker:
      - image: golangci/golangci-lint:v1.26
    steps:
      - checkout
      - run: golangci-lint run -v
workflows:
  version: 2
  build-workflow:
    jobs:
      - lint
      - build
